### ISSUE TITLE
UI freeze

### ISSUE THREAD

**Issue by Kwansy98** [Kwansy98/x64dbgCallFinder#2]
When the number of breakpoints is large, for example, when there are more than 1000, the debugger ui is often blocked. Does anyone know why?

**Comment by PurityEmptiness** [comment]
这个插件挺好用的，但是使用后自己下的断点不能保存了，每次重载自己下的断就被清空了，可能有冲突？我把插件移出去就可以正常保存下的断点了。然后是否支持下可以对指定dll进行扫描，不然dll数量多的时候会很慢很慢。。。
