### ISSUE TITLE
这个插件挺好用的，但是使用后自己下的断点不能保存了，每次重载自己下的断就被清空了，可能有冲突？我把插件移出去就可以正常保存下的断点了。然后是否支持下可以对指定dll进行扫描，不然dll数量多的时候会很慢很慢。。。

### ISSUE THREAD

**Issue by Kwansy98** [Kwansy98/x64dbgCallFinder#3]
这个插件挺好用的，但是使用后自己下的断点不能保存了，每次重载自己下的断就被清空了，可能有冲突？我把插件移出去就可以正常保存下的断点了。然后是否支持下可以对指定dll进行扫描，不然dll数量多的时候会很慢很慢。。。

_Originally posted by @lock111 in https://github.com/Kwansy98/x64dbgCallFinder/issues/2#issuecomment-1716854647_

**Comment by Kwansy98** [comment]
因为插件会设置很多断点，下次调试开始的时候自动删除所有断点，导致把用户自己的断点也删掉了。改成只删除插件设置的断点比较好。

**Comment by PurityEmptiness** [comment]
作者还更新这个插件吗？有空的话更新下可以对指定dll进行扫描呢？

**Comment by Kwansy98** [comment]
> 作者还更新这个插件吗？有空的话更新下可以对指定dll进行扫描呢？

已更新

**Comment by PurityEmptiness** [comment]
作者辛苦了！66666
